services:
  - type: web
    name: event-management-app
    runtime: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://srv1880.hstgr.io:3306/u518745130_CEM
      - key: SPRING_DATASOURCE_USERNAME
        value: u518745130_aathif
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false # Set this manually in Render dashboard
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_SECURITY_REMEMBER_ME_KEY
        sync: false # Set this manually in Render dashboard
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
